### ISSUE TITLE
Missing Information

### ISSUE THREAD

**Issue by EddyMI3d** [eyal0/OctoPrint-TimeToFilament#10]
Hello!

Nice project and neat idea!
But you may point out somewhere, that **Print-Time-Genius** is essential for this plugin.

Greetings

**Comment by eyal0** [comment]
Yes. I put it in the setup so I think that OctoPrint should fail to install this unless PTG is installed. I will test this and all make the requirement more obvious.

**Comment by EddyMI3d** [comment]
I think a short notification on the OctoPrint repository (https://plugins.octoprint.org/plugins/TimeToFilament/) and on github (https://github.com/eyal0/OctoPrint-TimeToFilament) would be good.
