### ISSUE TITLE
No entries in Settings, no time Display

### ISSUE THREAD

**Issue by Master-68** [eyal0/OctoPrint-TimeToFilament#13]
Doesn't seem to work... Running on OctoPI (all current updates for current stabe version 1.5.2 installed, Current version of PrintTimeGenius is also installed)

Pls. see screenshots:

![OctoPrint-PrintTimeGenius](https://user-images.githubusercontent.com/71970028/104910782-1fdf0300-598a-11eb-9559-90e136b927af.jpg)
![OctoPrint-TimeToFilament](https://user-images.githubusercontent.com/71970028/104910785-20779980-598a-11eb-9aa9-ec7407869d82.jpg)
![OctoPrint-TimeToFilament-2](https://user-images.githubusercontent.com/71970028/104910787-21103000-598a-11eb-8737-d0b1752e5dd7.jpg)

System information:

browser.user_agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:84.0) Gecko/20100101 Firefox/84.0
connectivity.connection_check: 8.8.8.8:53
connectivity.connection_ok: true
connectivity.enabled: true
connectivity.online: true
connectivity.resolution_check: octoprint.org
connectivity.resolution_ok: true
env.hardware.cores: 4
env.hardware.freq: 1500
env.hardware.ram: 4041732096
env.os.bits: 32
env.os.id: linux
env.os.platform: linux2
env.plugins.pi_support.model: Raspberry Pi 4 Model B Rev 1.2
env.plugins.pi_support.octopi_version: 0.17.0
env.plugins.pi_support.throttle_state: 0x0
env.python.pip: 19.3.1
env.python.version: 2.7.16
env.python.virtualenv: true
octoprint.safe_mode: false
octoprint.version: 1.5.2
printer.firmware: Prusa-Firmware 3.9.2 based on Marlin

**Comment by eyal0** [comment]
Seems like the same problem as #11. Does it work in English? He also had German.

I'm not sure how to configure German. How do I confugure German so that I can test this also?

**Comment by Master-68** [comment]
To be honest, I'm not really sure how to change the language... I guess it should be possible to change the language here, but I tried to change to english and it had no effect. But maybe I just haven't installed the correct language packs when I set up OctoPI...

![OctoPrint_language_settings](https://user-images.githubusercontent.com/71970028/104929456-31350900-59a4-11eb-8cdd-dd577fda3300.jpg)

**Comment by Master-68** [comment]
Just found, that you can change the language in the OctoPrint User settings:

![OctoPrint-userSettings](https://user-images.githubusercontent.com/71970028/104931269-778b6780-59a6-11eb-994b-285735aa6e97.jpg)

It seems the settings are displayed, when language is set to English!
