### ISSUE TITLE
Not an issue :)

### ISSUE THREAD

**Issue by KenLucke** [eyal0/OctoPrint-TimeToFilament#24]
Not an issue, just showing a bit of color I added:

<img width="423" alt="image" src="https://user-images.githubusercontent.com/57936294/115155762-22f39900-a036-11eb-9bbb-af4e9188d5c4.png">

**Comment by eyal0** [comment]
Nice one.  Did you modify the settings so that there would be `<span color=red>` tags in the output?  Or something like that?

**Comment by KenLucke** [comment]
Yep, exactly what I did.

```
Filament change in <b><span style="color:lime">${formatDuration(this.progress.printTimeLeft - this.plugins.TimeToFilament["^M600"].timeLeft)} </span></b>
<br>
Filament change at <b><span style="color:orange">${new Date(Date.now() + (this.progress.printTimeLeft - this.plugins.TimeToFilament["^M600"].timeLeft)*1000).toLocaleTimeString([], {hour12:false})}</span></b>
```
