### ISSUE TITLE
"Time to Next Layer" not displaying...

### ISSUE THREAD

**Issue by puterboy** [eyal0/OctoPrint-TimeToFilament#30]
Unless I am missing something, I don't see the "Time to Next Layer" displaying even though it is checked in the settings.
I am printing with a Prusa MK3S+

![Screenshot 2022-08-26 022455](https://user-images.githubusercontent.com/1993858/186836452-c5b61a96-9977-4387-a4fd-2337369323ad.png)

**Comment by puterboy** [comment]
OK. I figured out the problem...
Prusa printers use a different comment to signal a layer change --- "^;LAYER_CHANGE"

So use the following settings to get it to work for Prusa printers:

Description: Time to Next Layer
Regex: ^;LAYER_CHANGE
Format: Next layer in <b>${formatDuration(this.progress.printTimeLeft - this.plugins.TimeToFilament["^;LAYER_CHANGE"].timeLeft)}</b>

This may be helpful to add to the documentation...

**Comment by eyal0** [comment]
It's not the printer that is using a different format, it's the generator of the stl file.  So like, Cura versus Prusa slicer, etc.

**Comment by eyal0** [comment]
If you can send me a sample file and I can adjust the default config to support that other format of layer change.

**Comment by puterboy** [comment]
The gcode is ridiculously simple. As per the regex in my previous post, the layer change line simply looks like:
```;LAYER_CHANGE```

Part of the reason I suggested a feature request to track the number of matches as of the current position is so that one could add a layer number to the layer detection since Prusa slicer default layer change comment doesn't include the layer number.

**Comment by eyal0** [comment]
Ah, I see! There's no number! Hmm. I'll have to think about how to fix this!

**Comment by puterboy** [comment]
That's why I was thinking it would be helpful to have a general utility that could count instances :)
